name: lightgaussian
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pytorch-cuda=12.4
  - plyfile=0.8.1
  - python=3.9
  - pip=22.3.1
  - pytorch=2.4.0
  - torchaudio=2.4.0
  - torchvision=0.19.0
  - setuptools=69.5.1
  - tqdm
  - icecream
  - pip:
    - submodules/compress-diff-gaussian-rasterization
    - submodules/simple-knn
